# https://gist.github.com/joffilyfe/1a99250cb74bb75e29cbe8d6ca8ceedb
version: '3'

services:
  traefik:
    image: traefik:1.7-alpine
    ports:
      - 80:80
      - 8080:8080
    labels:
      - "traefik.frontend.rule=Host:monitor.sven.io"
      - "traefik.port=8080"
      - "traefik.backend=traefik"
      - "traefik.default.protocol=http"
      - "traefik.enable=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml:ro
    # command:
    #   - '--configFile=/etc/traefik/traefik.toml \'
    networks:
      - gitea-network

  portainer:
    image: portainer/portainer:latest
    command: --admin-password "$$2y$$05$$5n9/hh1FeHpLjyYLuNDTYuRobRpoR2RAx0zxzzQPqya9aBn.aFcHq"
    ports:
      - 9910
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/portainer:/data
    labels:
      - "traefik.frontend.rule=Host:portainer.sven.io"
      - "traefik.port=9000"
      - "traefik.backend=portainer"
      - "traefik.default.protocol=http"
      - "traefik.enable=true"
    networks:
      - gitea-network

  gitea:
    image: gitea/gitea:latest
    environment:
      - USER_UID=1000
      - USER_GID=1000
    labels:
      - "traefik.frontend.rule=Host:git.sven.io"
      - "traefik.port=3000"
      - "traefik.backend=git"
      - "traefik.default.protocol=http"
      - "traefik.enable=true"
    restart: always
    networks:
      - gitea-network
    volumes:
      - ./data/gitea:/data
    ports:
      - "3000:3000"
      - "222:22"

  drone:
    image: drone/drone
    restart: always
    depends_on:
      - gitea
    volumes:
      - ./data/drone:/var/lib/drone/
    environment:
      - DRONE_OPEN=false
      - DRONE_HOST=http://ci.sven.io
      - DRONE_SECRET=foobar
      # Gitea Config
      - DRONE_GITEA=true
      - DRONE_GITEA_URL=http://172.20.0.2:3000
      - DRONE_GITEA_GIT_USERNAME=sven
      - DRONE_GITEA_GIT_PASSWORD=gammel3
      # Set to true to disable SSL verification.
      - DRONE_GITEA_SKIP_VERIFY=true
      - DRONE_NETWORK=gitea-network
      - DRONE_SERVER_PROTO=http
      - DRONE_ADMIN=sven
    networks:
      - gitea-network
    ports:
      - "9000"
      - "8000:8000"
    labels:
      - "traefik.backend=drone"
      - "traefik.frontend.rule=Host:ci.sven.io"
      - "traefik.docker.network=proxy"
      - "traefik.port=8000"
      - "traefik.enable=true"
      - "traefik.default.protocol=http"

  drone-agent:
    image: drone/agent
    restart: always
    depends_on:
      - drone
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=drone:9000
      - DRONE_SECRET=foobar
      - DRONE_MAX_PROCS=3
    networks:
      - gitea-network

networks:
  gitea-network:
    external:
      name: gitea-network
