defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
    address = ":80"

    [entryPoints.http.redirect]
      entryPoint = "https"
      permanent = true

  [entryPoints.https]
    address = ":443"
    compress = true
      [entryPoints.https.tls]
        [[entryPoints.https.tls.certificates]]
        certFile = "/etc/traefik/certs/cert.crt"
        keyFile = "/etc/traefik/certs/cert.key"

# Enable Docker configuration backend
[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "local"
watch = true
exposedbydefault = false

